### PR TITLE
fix missing _read_exact

### PR DESCRIPTION
**Pull request by AnthraX1**

### CODE REVIEW

**Comment by timhughes** [comment]
Thanks for the pull request. Is it possible to write a test for this change as it obviously wasn't tested previously

**Comment by timhughes** [comment]
Need to look into this more. It looks like they have made some changes upstream in 3.11 that we need to take into account https://github.com/python/cpython/commit/ea23e7820f02840368569db8082bd0ca4d59b62a#diff-ad9b54ac8ef847cbb11fb0550f7e8cede55b1d92de15899e0a885a94a124838aR406

**Comment by mayankjobanputra** [comment]
I would really appreciate if we could merge this PR. I am hitting the same issue on 3.11.

**Review by timhughes — APPROVED** [review]
I have had time to read over and understand this. Upstream has extracted this into a static function along with [ _read_gzip_header](https://github.com/python/cpython/blob/ea23e7820f02840368569db8082bd0ca4d59b62a/Lib/gzip.py#L422) At some time we should just import those functions and fix the classes to use the imported versions but but that will only work on python>=3.11.

**Pull request merged**
